<a href="https://colab.research.google.com/github/Amedelokossou/Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipuler des données avec Pandas

In [ ]:
import pandas as pd

In [ ]:
!mkdir datasets

In [ ]:
! wget https://github.com/kevindegila/data-analyst/blob/main/datasets/movie.csv .0 datasets/movie.csv

--2026-06-24 16:04:03--  https://github.com/kevindegila/data-analyst/blob/main/datasets/movie.csv
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘movie.csv’

movie.csv               [ <=>                ] 231.40K  --.-KB/s    in 0.05s

2026-06-24 16:04:03 (4.54 MB/s) - ‘movie.csv’ saved [236954]

--2026-06-24 16:04:03--  http://.0/
Resolving .0 (.0)... failed: Name or service not known.
wget: unable to resolve host address ‘.0’
--2026-06-24 16:04:03--  http://datasets/movie.csv
Resolving datasets (datasets)... failed: Name or service not known.
wget: unable to resolve host address ‘datasets’
FINISHED --2026-06-24 16:04:03--
Total wall clock time: 0.9s
Downloaded: 1 files, 231K in 0.05s (4.54 MB/s)

In [ ]:
dossier = 'datasets/'

In [ ]:
dossier +'movie.csv'

'datasets/movie.csv'

In [ ]:
movie = pd.read_csv(dossier +'movie.csv')
movie

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/movie.csv'

In [ ]:
type(movie)

In [ ]:
movie.head() # montre par defaut les 5 premières lignes

In [ ]:
movie.head(10) # montre  les 10 premières lignes

In [ ]:
movie.columns   # Pour avoir les noms des colonnes

In [ ]:
type(movie.columns )

In [ ]:
movie.index   #pour avoir les indexes

In [ ]:
movie.values    #pour avoir les valeurs

In [ ]:
type(movie.values)

In [ ]:
movie.values.shape

In [ ]:
movie.values.ndim

#Quelques fonctions et méthodes pour mieux comprendre la dataframe

In [ ]:
movie.tail()    #pour voir les 5 dernières lignes

In [ ]:
movie.tail(6)    #pour voir les 6 dernières lignes

In [ ]:
movie.sample(5)   #pour voir 5 lignes aléatoire

In [ ]:
movie.dtypes    #Pour voir le type de chaque colonne

In [ ]:
movie.info()    #pour avoir les info sur les données

In [ ]:
movie.color   #Pour accéder à une colonne spécifique ici la colonne color

In [ ]:
movie['color']

In [ ]:
movie.language    #"Pour avoir le nombre de modalités"

In [ ]:
movie.language.unique() #Pour avoir les modalités au sein de language

In [ ]:
len(movie.language.unique())      #Nombre de modalités unique

In [ ]:
movie.language.nunique()

In [ ]:
movie.color.value_counts()  #Proportion de chaque valeur unique

In [ ]:
movie.language.value_counts()

In [ ]:
movie.language.value_counts(ascending=True)

In [ ]:
movie.language.value_counts(normalize=True) * 100   # Pour avoir les pourcentages des modalités

In [ ]:
movie.rename(columns= {'director_facebook_likes' : 'director_fb_likes'}, inplace=True)  #Renommer les colonnes

In [ ]:
movie.info()

In [ ]:
movie_string = movie.select_dtypes('object')    #Pour sélectionner toutes les variables qui sont de type "object"
movie_string.head()

In [ ]:
movie_string.describe()    #Pour avoir les statistiques descriptives

In [ ]:
movie_number = movie.select_dtypes('number')    #Pour sélectionner toutes les variables qui sont de type "object"
movie_number

In [ ]:
movie_number.describe()    #Pour avoir les statistiques descriptives

In [ ]:
cols_interest =['director_name', 'duration', 'gross', 'genres', 'movie_title', 'plot_keywords', 'budget', 'title_year', 'language', 'imdb_score']      #Pour sélectionner des colonnes d'interêt
movie_reduced = movie[cols_interest]
movie_reduced.head()

In [ ]:
movie_reduced.drop(0, inplace = True)

In [ ]:
movie_reduced.head()

In [ ]:
movie_reduced = movie_reduced.drop(['movie_title', 'plot_keywords'], axis = 1)
movie_reduced.head()

In [ ]:
movie_reduced['title'] = movie['movie_title'] + ' - ' + movie['director_name']  # comment créer une colonne
movie_reduced.head()

#Manipulation des données

In [ ]:
movie.head()

In [ ]:
movie.columns

In [ ]:
movie['movie_title']

In [ ]:
type(movie['movie_title'])

In [ ]:
movie.columns

In [ ]:
liste_des_colonnes = ['movie_title', 'language', 'director_name']
movie[liste_des_colonnes]

#Selectionner une ligne avec iloc

In [ ]:
movie.head(

)

In [ ]:
movie[0:2]

In [ ]:
movie.iloc[4]

In [ ]:
movie[0:10
      ]

In [ ]:
#Pour sélectionner les lignes 4,5,6,7

In [ ]:
movie.iloc[4:8]

In [ ]:
movie.iloc[[4, 45, 89, 12]]    #Selectionner les lignes 4, 45, 89, 12

In [ ]:
movie.iloc[4:8, 0:2]

In [ ]:
#Pour selectionner les colonnes qui aux positions : 3, 8, 6, 4

In [ ]:
movie.iloc[4:8, [3, 8, 6, 4]]

In [ ]:
movie.iloc[[5, 105, 74 ], [3, 8, 6, 4]]

#Selectionnes des colonnes et des lognes avec loc

In [ ]:
movie[0:10
      ]

In [ ]:
movie.loc[4:8, "color": "director_name"]

In [ ]:
movie.iloc[4:8, 0:2]

In [ ]:
movie.iloc[4:8, [3, 8, 6, 4]]

In [ ]:
colonnes = movie.columns.tolist()
print(colonnes)

In [ ]:
movie.columns[[3, 8, 6, 4]].tolist()

In [ ]:
movie.loc[4:7, ['duration', 'gross', 'actor_2_name', 'director_fb_likes']]

In [ ]:
movie.loc[4:7, 'duration': 'gross']

#Filtrer les lignes d'un dataframe

In [ ]:
# Sélectionner les films dont le directeur est "Doug Walker" afin de calculer plus tard le note moyenne des films qu'il a dirigé.
condition = movie['director_name'] == 'Doug Walker'
movie[condition]

In [ ]:
movie['director_name'].describe()

In [ ]:
condition = movie['director_name'] == 'Steven Spielberg'
steven = movie[condition]

In [ ]:
steven.head()

In [ ]:
steven['imdb_score']

In [ ]:
steven['imdb_score'].mean() #La moyenne des films de Steven

In [ ]:
#selectionner les films francais dont la duréée est inférieure à 1heure.
#language =francais
#duree < 1 heure
cond1 = movie['language'] == "French"
cond2 = movie['duration'] < 60
cond1

In [ ]:
movie[cond1 & cond2]

In [ ]:
movie[cond1 | cond2]

#Création de Dataframe

In [ ]:
import pandas as pd

In [ ]:
noms =['paul', 'radji', 'bob', 'alice']
ages =[41, 53, 56, 38]
poids = [12, 15.36, 98.25, 14.26]

In [ ]:
data ={
    'noms_col': noms,
    'ages_col': ages,
    'poids_col': poids
}

In [ ]:
data = pd.DataFrame(data)
data

In [ ]:
data.describe()

In [ ]:
data.sum(axis=0)

In [ ]:
data = [
    {
        'noms_col': 'paul',
        'ages_col': 41,
        'poids_col': 12
    },
    {
        'noms_col': 'radji',
        'ages_col': 53,
        'poids_col': 15.36
    },
    {
        'noms_col': 'bob',
        'ages_col': 56,
        'poids_col': 98.25
    },
]

In [ ]:
data

In [ ]:
df = pd.DataFrame(data)
df

In [ ]:
data = [
    {
        'noms_col': 'paul',
        'ages_col': 41,
        'poids_col': 12
    },
    {
        'noms_col': 'radji',
        'ages_col': 53,
        'poids_col': 15.36
    },
    {
        'noms_col': 'bob',
        'ages_col': 56,
        'poids_col': 98.25
        },
    {

        'poids_col': 14.26
    },
]

In [ ]:
df1 = pd.DataFrame(data)
df1

# Importation des données d'un site web

In [ ]:
import pandas as pd

In [ ]:
!pip install lxml

In [ ]:
import pandas as pd

url = 'https://wikipedia.org'

# Utilisation directe avec l'option de stockage
tables = pd.read_html('https://fr.wikipedia.org/wiki/Liste_des_pr%C3%A9sidents_des_%C3%89tats-Unis_par_long%C3%A9vit%C3%A9', storage_options={'User-Agent': 'Mozilla/5.0'})

In [ ]:
tables

In [ ]:
len(tables)

In [ ]:
df = tables[0]
df

In [ ]:
df.head()

In [ ]:
df.sample(10)

In [ ]:
df.columns

In [ ]:
df.set_index('No', inplace=True)
df

In [ ]:
df.sample(5)

# Travailler sur le TDB du PADMAR

In [ ]:
# 'https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_les_plus_peupl%C3%A9es'

import pandas as pd

url = 'https://wikipedia.org'

# Utilisation directe avec l'option de stockage
commune = pd.read_html('https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_les_plus_peupl%C3%A9es', storage_options={'User-Agent': 'Mozilla/5.0'})

In [ ]:
commune

In [ ]:
commune[1]

# Aggregations group by

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
auto = pd.read_csv('/content/datasets/Automobile_data.csv')
auto

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [ ]:
auto.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [ ]:
auto.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [ ]:
auto['body-style'].value_counts()

body-style
sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: count, dtype: int64

In [ ]:
auto.groupby('body-style')

In [ ]:
auto.groupby('body-style').groups

{'convertible': [0, 1, 72, 128, 172, 189], 'hardtop': [69, 74, 98, 126, 127, 167, 168, 170], 'hatchback': [2, 9, 18, 19, 21, 22, 23, 24, 29, 30, 31, 32, 33, 34, 37, 38, 46, 50, 51, 52, 55, 56, 57, 58, 59, 61, 64, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 95, 99, 104, 105, 106, 118, 119, 120, 124, 125, 129, 131, 132, 134, 136, 138, 139, 140, 150, 151, 152, 157, 159, 161, 164, 166, 169, 171, 175, 177, 178, 179, 190], 'sedan': [3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 20, 25, 26, 27, 35, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 53, 54, 60, 62, 63, 65, 66, 67, 70, 71, 73, 85, 86, 87, 88, 89, 90, 91, 92, 94, 96, 100, 101, 103, 107, 108, 111, 112, 115, 116, 117, 121, 122, 133, 135, 137, 141, 142, 143, 144, 145, 156, 158, 160, 162, 163, 165, 173, 174, 176, 180, 182, 183, 184, 185, 186, 187, 188, 191, 192, 194, 196, 198, 200, 201, 202, 203, 204], 'wagon': [7, 28, 36, 68, 93, 97, 102, 109, 110, 113, 114, 123, 130, 146, 147, 148, 149, 153, 154, 155, 181, 193, 195, 197, 199]}

In [ ]:
auto.groupby('body-style').groups.keys()

dict_keys(['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'])

In [ ]:
style = auto.groupby('body-style')

In [ ]:
style.get_group('hardtop') #pour avoir rtoutes les lignes ou on a hardtop

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
69,0,93,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,...,183,idi,3.58,3.64,21.5,123,4350,22,25,28176
74,1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.8,3.35,8.0,184,4500,14,16,45400
98,2,168,nissan,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249
126,3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,32528
127,3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,34028
167,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.3,116,4800,24,30,8449
168,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.3,116,4800,24,30,9639
170,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.3,116,4800,24,30,11199

In [ ]:
auto['drive-wheels'].value_counts()

drive-wheels
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64

In [ ]:
double_groupin = auto.groupby(['drive-wheels', 'body-style'])
double_groupin.groups

{('4wd', 'hatchback'): [9, 140], ('4wd', 'sedan'): [4, 144, 145], ('4wd', 'wagon'): [148, 149, 154, 155], ('fwd', 'convertible'): [189], ('fwd', 'hardtop'): [98], ('fwd', 'hatchback'): [18, 19, 21, 22, 23, 24, 29, 30, 31, 32, 33, 34, 37, 38, 50, 51, 52, 59, 61, 64, 76, 77, 78, 79, 80, 81, 82, 83, 84, 95, 99, 118, 119, 120, 131, 132, 134, 136, 138, 139, 150, 151, 152, 157, 159, 161, 175, 177, 190], ('fwd', 'sedan'): [3, 5, 6, 8, 20, 25, 26, 27, 35, 39, 40, 41, 42, 44, 45, 53, 54, 60, 62, 63, 85, 86, 87, 88, 89, 90, 91, 92, 94, 96, 100, 101, 103, 121, 122, 133, 135, 137, 141, 142, 143, 156, 158, 160, 162, 173, 174, 176, 182, 183, 184, 185, 186, 187, 188, 191, 192], ('fwd', 'wagon'): [7, 28, 36, 93, 97, 102, 123, 130, 146, 147, 153, 193], ('rwd', 'convertible'): [0, 1, 72, 128, 172], ('rwd', 'hardtop'): [69, 74, 126, 127, 167, 168, 170], ('rwd', 'hatchback'): [2, 46, 55, 56, 57, 58, 75, 104, 105, 106, 124, 125, 129, 164, 166, 169, 171, 178, 179], ('rwd', 'sedan'): [10, 11, 12, 13, 14, 15, 16, 17, 43, 47, 48, 49, 65, 66, 67, 70, 71, 73, 107, 108, 111, 112, 115, 116, 117, 163, 165, 180, 194, 196, 198, 200, 201, 202, 203, 204], ('rwd', 'wagon'): [68, 109, 110, 113, 114, 181, 195, 197, 199]}

In [ ]:
double_groupin.first()

                          symboling normalized-losses           make  \
drive-wheels body-style
4wd          hatchback            0                 ?           audi
             sedan                2               164           audi
             wagon                0                85         subaru
fwd          convertible          3                 ?     volkswagen
             hardtop              2               168         nissan
             hatchback            2               121      chevrolet
             sedan                2               164           audi
             wagon                1                 ?           audi
rwd          convertible          3                 ?    alfa-romero
             hardtop              0                93  mercedes-benz
             hatchback            1                 ?    alfa-romero
             sedan                2               192            bmw
             wagon               -1                93  mercedes-benz

                         fuel-type aspiration num-of-doors engine-location  \
drive-wheels body-style
4wd          hatchback         gas      turbo          two           front
             sedan             gas        std         four           front
             wagon             gas        std         four           front
fwd          convertible       gas        std          two           front
             hardtop           gas        std          two           front
             hatchback         gas        std          two           front
             sedan             gas        std         four           front
             wagon             gas        std         four           front
rwd          convertible       gas        std          two           front
             hardtop        diesel      turbo          two           front
             hatchback         gas        std          two           front
             sedan             gas        std          two           front
             wagon          diesel      turbo         four           front

                          wheel-base  length  width  ...  engine-size  \
drive-wheels body-style                              ...
4wd          hatchback          99.5   178.2   67.9  ...          131
             sedan              99.4   176.6   66.4  ...          136
             wagon              96.9   173.6   65.4  ...          108
fwd          convertible        94.5   159.3   64.2  ...          109
             hardtop            95.1   162.4   63.8  ...           97
             hatchback          88.4   141.1   60.3  ...           61
             sedan              99.8   176.6   66.2  ...          109
             wagon             105.8   192.7   71.4  ...          136
rwd          convertible        88.6   168.8   64.1  ...          130
             hardtop           106.7   187.5   70.3  ...          183
             hatchback          94.5   171.2   65.5  ...          152
             sedan             101.2   176.8   64.8  ...          108
             wagon             110.0   190.9   70.3  ...          183

                          fuel-system  bore stroke  compression-ratio  \
drive-wheels body-style
4wd          hatchback           mpfi  3.13    3.4                7.0
             sedan               mpfi  3.19    3.4                8.0
             wagon               2bbl  3.62   2.64                9.0
fwd          convertible         mpfi  3.19    3.4                8.5
             hardtop             2bbl  3.15   3.29                9.4
             hatchback           2bbl  2.91   3.03                9.5
             sedan               mpfi  3.19    3.4               10.0
             wagon               mpfi  3.19    3.4                8.5
rwd          convertible         mpfi  3.47   2.68                9.0
             hardtop              idi  3.58   3.64               21.5
             hatchback           mpfi  2.68   3.47                9.0
             sedan               mpfi   3.5    2.8                8.8
             wagon                idi  3.58   3.64               21.5

                         horsepower peak-rpm city-mpg  highway-mpg  price
drive-wheels body-style
4wd          hatchback          160     5500       16           22      ?
             sedan              115     5500       18           22  17450
             wagon               82     4800       23           29   8013
fwd          convertible         90     5500       24           29  11595
             hardtop             69     5200       31           37   8249
             hatchback           48     5100       47           53   5151
             sedan              102     5500       24           30  13950
             wagon              110     5500       19           25  18920
rwd          convertible        111     5000       21           27  13495
             hardtop            123     4350       22           25  28176
             hatchback          154     5000       19           26  16500
             sedan              101     5800       23           29  16430
             wagon              123     4350       22           25  28248

[13 rows x 24 columns]

#Les valeurs manquantes

In [21]:
import pandas as pd
import numpy as np

In [26]:
data = np.arange(15,30).reshape(5, 3)
dfx = pd.DataFrame(data, index = ['apple', 'banana', 'kiwi', 'grapes', 'mango'] , columns=['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [27]:
dfx['store4'] = np.nan
dfx

        store1  store2  store3  store4
apple       15      16      17     NaN
banana      18      19      20     NaN
kiwi        21      22      23     NaN
grapes      24      25      26     NaN
mango       27      28      29     NaN

In [29]:
dfx.loc['apple']

store1    15.0
store2    16.0
store3    17.0
store4     NaN
Name: apple, dtype: float64

In [30]:
dfx.loc['orange'] = np.arange(15, 19)
dfx

        store1  store2  store3  store4
apple       15      16      17     NaN
banana      18      19      20     NaN
kiwi        21      22      23     NaN
grapes      24      25      26     NaN
mango       27      28      29     NaN
orange      15      16      17    18.0

In [31]:
dfx.loc['strawberry'] = np.nan
dfx

            store1  store2  store3  store4
apple         15.0    16.0    17.0     NaN
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
orange        15.0    16.0    17.0    18.0
strawberry     NaN     NaN     NaN     NaN

In [32]:
dfx['store5'] = np.nan
dfx

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

In [33]:
dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False    True    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
orange       False   False   False   False    True
strawberry    True    True    True    True    True

In [34]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    6
store5    7
dtype: int64

In [36]:
(dfx.isnull().mean())*100  #Pourcentage de données manquantes par colonnes

store1     14.285714
store2     14.285714
store3     14.285714
store4     85.714286
store5    100.000000
dtype: float64

In [37]:
dfx.isnull().mean(axis=0)

store1    0.142857
store2    0.142857
store3    0.142857
store4    0.857143
store5    1.000000
dtype: float64

In [38]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True   False   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
orange        True    True    True    True   False
strawberry   False   False   False   False   False

In [39]:
dfx.notnull().mean(axis=0)

store1    0.857143
store2    0.857143
store3    0.857143
store4    0.142857
store5    0.000000
dtype: float64

In [ ]:
# Supprimer les données manquantes avec dropna()

In [40]:
dfx.dropna() #Supprime toutes les lignes du dataframe car toutes les lignes ont au moins une valeur manquante

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [41]:
dfx

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

In [45]:
dfx.dropna(how = "all") # Supprime toutes les lignes dont toutes les colonnes sont manquantes donc strawberry

        store1  store2  store3  store4  store5
apple     15.0    16.0    17.0     NaN     NaN
banana    18.0    19.0    20.0     NaN     NaN
kiwi      21.0    22.0    23.0     NaN     NaN
grapes    24.0    25.0    26.0     NaN     NaN
mango     27.0    28.0    29.0     NaN     NaN
orange    15.0    16.0    17.0    18.0     NaN

In [46]:
dfx.dropna(how = "all", axis = 1)   #Supprime la colonne qui n'a que des données manquantes dons store 5

            store1  store2  store3  store4
apple         15.0    16.0    17.0     NaN
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
orange        15.0    16.0    17.0    18.0
strawberry     NaN     NaN     NaN     NaN

In [48]:
dfx.dropna(thresh= 5, axis = 1)     # Si dans une colonne on a 5 données manquantes, alors supprime

            store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
orange        15.0    16.0    17.0
strawberry     NaN     NaN     NaN

In [49]:
dfx

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

Remplacer les données manquantes on utilise fillna(0) pour lui demander de remplacer nan par

In [50]:
dfx.fillna(0)

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     0.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
orange        15.0    16.0    17.0    18.0     0.0
strawberry     0.0     0.0     0.0     0.0     0.0

In [51]:
dfx

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

In [54]:
dfx.mean(axis=0)

store1    20.0
store2    21.0
store3    22.0
store4    18.0
store5     NaN
dtype: float64

In [56]:
dfx.fillna(dfx.mean())    #Pour faire une imputation par la moyenne

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    18.0     NaN
banana        18.0    19.0    20.0    18.0     NaN
kiwi          21.0    22.0    23.0    18.0     NaN
grapes        24.0    25.0    26.0    18.0     NaN
mango         27.0    28.0    29.0    18.0     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry    20.0    21.0    22.0    18.0     NaN

In [57]:
#backward forward fill
dfx

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

In [58]:
dfx.store4.fillna(method='ffill')      #dans la colonne store4 , remplacer une données manquantes par cette de ligne suivante qui est non nan

/tmp/ipykernel_3718/772095115.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='ffill')      #dans la colonne store4 , remplacer une données manquantes par cette de ligne suivante qui est non nan

apple          NaN
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
orange        18.0
strawberry    18.0
Name: store4, dtype: float64

In [59]:
dfx.store4.fillna(method='bfill') #Pour faire une backword fill

/tmp/ipykernel_3718/2174360155.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='bfill')

apple         18.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
orange        18.0
strawberry     NaN
Name: store4, dtype: float64

In [60]:
#Faire une interpollation de données manquantes.

n_ventes = pd.Series([100, np.nan, np.nan, 200, np.nan, 150]
                     )
n_ventes.interpolate()

0    100.000000
1    133.333333
2    166.666667
3    200.000000
4    175.000000
5    150.000000
dtype: float64